 <?php

/**
 * Implementation of hook_menu
 */
function mapbox_geostats_menu() {

    $items['all-ages-map'] = array(
        'title'           => t('Global Vision Database Maps (All ages)'),
        'page callback'   => 'theme',
        'page arguments'  => array('all-ages-mapbox-geostats-map'),
        'access callback' => true,
        'type'            => MENU_CALLBACK
    );

    $items['adults-over-50-map'] = array(
        'title'           => t('Global Vision Database Maps (Adults > 50)'),
        'page callback'   => 'theme',
        'page arguments'  => array('adult-mapbox-geostats-map'),
        'access callback' => true,
        'type'            => MENU_CALLBACK
    );

    return $items;

}


/**
 * Implementation of hook_theme
 */
function mapbox_geostats_theme($existing, $type, $theme, $path) {

    return array(
        'all-ages-mapbox-geostats-map' => array(
            'template'  => 'all-ages-map',
            'path'      => drupal_get_path('module', 'mapbox_geostats') . '/templates',
            'variables' => array()
        ),
        'adult-mapbox-geostats-map' => array(
            'template'  => 'adults-over-50-map',
            'path'      => drupal_get_path('module', 'mapbox_geostats') . '/templates',
            'variables' => array()
        )
    );

}
